apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sauce-connect.fullname" . }}
  labels:
    {{- include "sauce-connect.labels" . | nindent 4 }}
data:
  sauce-connect.yaml: |
    username: {{ .Values.config.username | default "default-username" }}
    region: {{ .Values.config.region | default "us-west" }}
    access-key: {{ .Values.env.SAUCE_CONNECT_API_KEY | default "default-access-key" | quote }}
    tunnel-name: {{ .Values.config.tunnelName | default "default-tunnel" }}
  {{- $config := omit .Values.config "enabled" }}
  {{- toYaml $config | default "{}" | nindent 4 }}
  {{- range $key, $value := .Values.templates }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}